### ISSUE TITLE
Maven ->The following artifacts could not be resolved

### ISSUE THREAD

**Issue by qianlei6148** [chigix/Chizuru#1]
“The following artifacts could not be resolved: com.chigix:netty-router:jar:3.3.9, Could not find artifact com.chigix:netty-router:jar:3.3.9 in central (https://repo.maven.apache.org/maven2) -> [Help 1]”
I use maven to build project ,this situation makes maven build failure.How to solve.
Thank you!

**Comment by chigix** [comment]
There are two maven libraries at snapshot are involved in this project, which means that these projects are still not available through maven central repository and of course the error that downloading failed  occurred in your console.

* https://github.com/sinetja/netty-router/tree/3.3
    You could directly clone this project and execute `maven install -DskipTests`. This project is a pure Netty Plugin projects without any other dependencies, which makes you could pass this building and installation as my expectation.
* https://github.com/mapstruct/mapstruct
    You also have to clone this project into your local directory and execute `mvn clean install -DskipDistribution=true`, which will help you install mapstruct:1.3.0-snapshot version.

After the both project installed, building of this project is able to be passed I think.

**Comment by qianlei6148** [comment]
Awesome! Successful!
Thank you.
